seoulmate7/Seoulmate_Frontend

.coderabbit.yaml

closed #5 
- 코드래빗 설정
- coderabbit.yml 파일 추가

Chore: coderabbit.yml 파일 추가

---

src/pages/search/SearchHobby.tsx

fix: SearchHobby.tsx에서 백 화살표 이미지의 import 경로 수정
fix: SearchHobby.tsx에서 백 화살표 이미지의 import 경로 수정
- [x ] Bugfix

fix: SearchHobby.tsx에서 백 화살표 이미지의 import 경로 수정

---

package-lock.json
package.json
src/components/signup/hobby/InterestSelector.tsx
src/components/signup/profile/ProfileImageUpload.tsx
src/pages/HobbySelectionPage.tsx
src/pages/SchoolVerificationPage.tsx
src/pages/SchoolVerifyPage.tsx
src/pages/SignUpLangTestPage.tsx
src/pages/SignUpPage.tsx
src/pages/SignUpProfilePage.tsx

앱 접속 시 화면 구성이 깨지는 현상 수정
1. 전체적인 페이지 테두리 삭제
2. 앱 호환성 고려 개발
3. datePicker, date-fns 라이브러리 추가

design: 디자인 수정 및 datePicker, date-fns 라이브러리 추가

---

src/pages/SignUpProfilePage.tsx

design: 입력창 오른쪽 정렬 수정

---

src/components/common/FloatingActionButton.tsx
src/components/createMeeting/CategoryDropdown.tsx
src/components/createMeeting/CategoryModal.tsx
src/components/createMeeting/PhotoUploadSection.tsx
src/pages/CreateMeeting/CreateMeeting.tsx

close #42 
사설 모임 생성 페이지 완성
📝 Changes
🆕 새로운 컴포넌트 추가
ParticipantField: 최소/최대 인원수 입력 컴포넌트 (정수만 입력 가능, 1 이상 제한)
ChargeField: 참가비 입력 컴포넌트 (null 허용으로 placeholder 표시)
🔧 기존 컴포넌트 개선
CategoryDropdown: 드롭다운에서 모달 방식으로 변경, 최대 5개 선택 제한, 토스트 알림 추가
CategoryModal: framer-motion 애니메이션, 다중 선택 UI, 스크롤바 숨김 처리
LanguageDropdown: 다중 선택 지원, 체크박스 UI, 스크롤바 숨김, 드롭다운 회전 애니메이션
PhotoUploadSection: framer-motion 카메라 아이콘 애니메이션 효과
CreateMeetingButton: vh 단위 적용, transition 애니메이션 개선
🔍 유효성 검사
모든 필드 필수 입력 검증
최소인원 ≤ 최대인원 조건 확인
참가비 0 이상 제한
언어 및 카테고리 최소 1개 이상 선택
🔎 PR Type

Feat/#42 사설 모임 생성

---

src/components/home/modal/FriendsModal.tsx

모바일에서 모달창이 화면 밖으로 나감
모바일에서 모달창이 화면 밖으로 나감 현상 수정
height 100일 때 100dvh가 되도록 추가

fix: 모달창이 화면 위로 나가는 현상 수정

---

src/components/home/modal/FriendsModal.tsx

모바일에서 모달창이 화면 밖으로 나감
모바일에서 모달창이 화면 밖으로 나감 현상 수정
height 100일 때 100dvh가 되도록 추가

fix/#58 모달창이 화면 밖으로 나가는 현상 수정

---

src/components/common/HeaderSeoulmate.tsx
src/components/common/NoFixedHeaderSeoulmate.tsx
src/pages/MyPage/MyHobby.tsx
src/pages/MyPage/MyProfile.tsx

#80 
알림 클릭 시 /alarm으로 이동
알림 클릭 시 /alarm으로 이동

Feat/#80 채팅목록, 알림창

---

src/components/modal/FriendsModal.tsx

모바일로 접속 시 모달창 크기가 좁게 나옴 현상
모달창 너비 w-full 추가

chore: 모달창 너비 크기 변경

---

src/components/common/NoAlarmBackHeader.tsx
src/components/createMeeting/CategoryModal.tsx
src/components/search/ActiveSearchClub.tsx
src/pages/alarm/AlarmPage.tsx
src/pages/schedule/Schedule.tsx
src/pages/search/SearchHobby.tsx

[Fix: NoAlarmBackHeader에서 showBorder 속성을 false로 설정하여 경계선 숨김]
[Fix: NoAlarmBackHeader에서 showBorder 속성을 false로 설정하여 경계선 숨김]

 Fix: NoAlarmBackHeader에서 showBorder 속성을 false로 설정하여 경계선 숨김 

---

src/components/chat/ChatListBox.tsx
src/pages/chat/ChatList.tsx

#94 
Fix: ChatListBox에서 onClick 속성을 추가하여 클릭 시 채팅방으로 이동 기능 구현
Fix: ChatListBox에서 onClick 속성을 추가하여 클릭 시 채팅방으로 이동 기능 구현

Fix: ChatListBox에서 onClick 속성을 추가하여 클릭 시 채팅방으로 이동 기능 구현

---

src/App.tsx
src/components/home/class/Info.tsx
src/components/home/club/ClubCard.tsx
src/components/home/club/MeetingInfo.tsx
src/components/home/club/ParticpantsList.tsx
src/pages/home/ClassDetailPage.tsx
src/pages/home/HomePage.tsx

사설 상세보기 페이지 추가
사설 상세보기 페이지 추가
기존 클래스 페이지 재사용

design: 사설모임 상세보기 페이지 추가

---

src/pages/signUp/AuthRedirect.tsx
src/pages/signUp/SignUpProfilePage.tsx

기존회원 시 홈페이지 이동
기존회원 시 홈페이지 이동 추가

feat: 기존 회원 바로 홈페이지 navigate하도록 추가

---

src/pages/chat/ChatList.tsx
src/pages/chat/ChatRoom.tsx
src/pages/friend/FriendPage.tsx
src/pages/schedule/Schedule.tsx

[FIX] 친구 페이지 검색 로직 수정 #184

---

src/components/modal/Friends.tsx

closed #194 
- 친구에게 1:1 메시지 보내기 연동
- `Friends`, ...

[FEATURE] 친구에게 1:1 메시지 보내기 연동

---

src/components/chat/ChatListBox.tsx
src/pages/chat/ChatList.tsx
src/pages/chat/ChatRoom.tsx

[FEATURE] 채팅 안 읽은 개수 추가 #196

---

src/components/modal/ActionButton.tsx
src/components/modal/FriendRequestModal.tsx
src/components/modal/Friends.tsx

친구 모달창 친구 상태값 UI 변경
친구 모달창 친구 상태값 UI 변경

design: 친구 모달창 친구 상태값 UI 변경

---

src/components/home/ActionButton.tsx
src/pages/home/ClassDetailPage.tsx
src/pages/home/ClubDetailPage.tsx

참여중 여부 변경 및 그룹채팅 조건 변경
참여중 여부 변경 및 그룹채팅 조건 변경

feat: 참여중 여부 변경 및 그룹채팅 조건 변경

---

src/components/home/ActionButton.tsx
src/pages/home/ClassDetailPage.tsx
src/pages/home/ClubDetailPage.tsx

feat: 호스트 참여 조건 변경

---

src/components/home/ActionButton.tsx
src/pages/home/ClubDetailPage.tsx

chore: 텍스트 비활성화 조건 추가

---

src/components/home/ActionButton.tsx

fix: 그룹채팅방 생성 로직 변경
